eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 30
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8030
spring:
  application:
    name: documentService
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/documentdb
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-plateform: org.hibernate.dialect.PostgreSQLDialect